# Generated by Django 5.1.1 on 2024-09-28 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="content",
        ),
    ]
